### ISSUE TITLE
Publishing Lambdas require a versioned S3 bucket.

### ISSUE THREAD

**Issue by Shockolate** [Cimpress-MCP/LambdaWrap#3]
The `publish_lambda_to_s3(local_lambda_file, bucket, key)` will fail if versioning is not enabled on the target S3 bucket.

Rather minor issue.

**Comment by thoean** [comment]
This is by design since LambdaWrap leverages S3 versions instead of forcing clients to introduce their custom version like `MyFunction.0.0.1.zip`.

However, it's a valid point that either the documentation has to improve (the readme file currently doesn't mention that), or that we could fail with a clear error message by checking the S3 bucket properties as part of this script. And long-term, it could even support both options by either using a version, and if not available, simply the current file.

**Comment by wparad** [comment]
One option could be to automatically manage the bucket via LambdaWrap, so the users won't ever see this behavior.  Versioning could be automatically added to the bucket, and also set up a lifecycle rule to delete old versions after 100 days or something like that, since AWS charges you the same for new versions as well as old.

Personally, I could get bedind "delete the whole object on new deployment" since all of my code is in source control, and if I want to deploy I need to retrigger deployment anyway, s3 is only there for convenience and I can deploy from there any way without breaking everything.

**Comment by thoean** [comment]
Good points regarding deleting old versions or automatically enable versioning. Both should however be opt-in since the first might delete an entry you want to use (unlikely, but still), and the latter might incur more costs depending what other data you have in that bucket.

Deleting and re-creating the whole object is tempting. However, versioning has the nice side-effect that two deployments can run concurrently without stealing each other's file.

My suggestion:
* The default is to fail loud when versioning isn't enabled.
* It has an optional parameter to auto-enable versioning if it's not enabled.
* If interest in this feature is high, support for versioned and non-versioned buckets could be added.

**Comment by Shockolate** [comment]
The Lambda API now supports uploading a zip file in the `CreateFunction` and `UpdateFunctionCode` actions. I see no reason why S3 is needed at all for the workflow, as long as Lambda Versions are published and Lambda Aliases are used.
Thoughts, @wparad @thoean ?

**Comment by wparad** [comment]
Agreed, want to make that improvement? Other libraries avoid uploading to S3, not sure it provides any additional value here.

**Comment by Shockolate** [comment]
I will make the improvement, but I expect this to be a breaking change.. Would like to release a major version to coincide with it

**Comment by Shockolate** [comment]
Resolved in #40
